### ISSUE TITLE
неверная кодировка

### ISSUE THREAD

**Issue by wsadqert** [wsadqert/sirius-leto#24]
# File
`/src/general/gui/windows/TextTaskListWindow.py`:17

# Traceback
UnicodeDecodeError: byte 0x98 pos 411

# Solution:
change encoding to `utf-8`

**Comment by matvejk** [comment]
аналогично
 src\general\gui\windows\BibligraphyWindow.py строка 11 (при попытке открыть список лит-ры)
 src\general\gui\windows\TextTaskListWindow.py строка 51 (при попытке открыть задачник)

**Comment by wsadqert** [comment]
solved #25 #26
