### ISSUE TITLE
no images + no formulas

### ISSUE THREAD

**Issue by matvejk** [wsadqert/sirius-leto#31]
task 8.5: in html there ARE images and mathjax formulas, but not working in python :(((((((((((((

Maybe try to steal code from taskbook file, there are working formulas, but not images

**Comment by wsadqert** [comment]
yes, idk why mathjax isn't working right now, several months ago it was working

**Comment by wsadqert** [comment]
maybe they change api, and i should update link in <head>, idk

**Comment by matvejk** [comment]
taskbook markdown still works

**Comment by wsadqert** [comment]
very strange. Maybe we really should copy code from taskbook...

**Comment by matvejk** [comment]
images still dont work there)

**Comment by wsadqert** [comment]
@matvejk was the problem resolved?

**Comment by matvejk** [comment]
Картинки, как я помню, починились. Но формулы нет. Вроде, решили их картинками вставлять12.11.2024, 02:00, "Matvey Polubryukhov" ***@***.***>:
@matvejk was the problem resolved?
