### ISSUE TITLE
амперметр работает некорректно

### ISSUE THREAD

**Issue by matvejk** [wsadqert/sirius-leto#41]
**ввод**
```python
# Example usage
circuit = Circuit()
circuit.add(VoltageSource(10, 'ground', 'node0'))
ammeter = Ammeter("node0", "node1")
circuit.add(ammeter)
circuit.add(Resistor(1, 'node1', 'ground'))
voltmeter = Voltmeter("node1", "ground")
circuit.add(voltmeter)


t_max = 0.001
time_step = 0.001

solver = circuit.get_solver(time_step)
final_voltages = solver.solve(t_max)

print(voltmeter.get_value())
print(ammeter.get_value())
```

цепь такая: 
![изображение](https://github.com/user-attachments/assets/cc50e551-b0ab-453c-b52d-48cf6ee6ed9d)

**ожидаемый результат**
10
10

**фактический результат**
9.99999800745108
**19.99999501123284**

**Comment by matvejk** [comment]
Запустил ещё раз, ничего не меняя. Всё сломалось :(
  
  
  0%|          | 0/1 [00:00<?, ?it/s]
┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ C:\Users\Матвей\Desktop\sirius-leto-master\src_drafts\lab5_circuit\main.py: │
│ 23 in <module>                                                              │
│                                                                             │
│   20 time_step = 0.001                                                      │
│   21                                                                        │
│   22 solver = circuit.get_solver(time_step)                                 │
│ > 23 final_voltages = solver.solve(t_max)                                   │
│   24                                                                        │
│   25 print(voltmeter.get_value())                                           │
│   26 print(ammeter.get_value())                                             │
│                                                                             │
│ ┌──────────────────────────────── locals ─────────────────────────────────┐ │
│ │             abc = <module 'components.abc' from                         │ │
│ │                   'C:\\Users\\Матвей\\Desktop\\sirius-leto-master\\src… │ │
│ │         Ammeter = <class 'components.instruments.Ammeter'>              │ │
│ │         ammeter = <components.instruments.Ammeter object at             │ │
│ │                   0x00000166CEEC72C0>                                   │ │
│ │       Capacitor = <class 'components.components.Capacitor'>             │ │
│ │         Circuit = <class 'solver.Circuit'>                              │ │
│ │         circuit = <solver.Circuit object at 0x00000166CEE9A360>         │ │
│ │      components = <module 'components.components' from                  │ │
│ │                   'C:\\Users\\Матвей\\Desktop\\sirius-leto-master\\src… │ │
│ │ components_list = [                                                     │ │
│ │                   │   '__name__',                                       │ │
│ │                   │   '__doc__',                                        │ │
│ │                   │   '__package__',                                    │ │
│ │                   │   '__loader__',                                     │ │
│ │                   │   '__spec__',                                       │ │
│ │                   │   '__path__',                                       │ │
│ │                   │   '__file__',                                       │ │
│ │                   │   '__cached__',                                     │ │
│ │                   │   '__builtins__',                                   │ │
│ │                   │   'abc',                                            │ │
│ │                   │   ... +8                                            │ │
│ │                   ]                                                     │ │
│ │           Diode = <class 'components.components.Diode'>                 │ │
│ │         install = <function install at 0x00000166CF061DA0>              │ │
│ │     instruments = <module 'components.instruments' from                 │ │
│ │                   'C:\\Users\\Матвей\\Desktop\\sirius-leto-master\\src… │ │
│ │          pprint = <function pprint at 0x00000166C6AF5120>               │ │
│ │        Resistor = <class 'components.components.Resistor'>              │ │
│ │          solver = <solver.CircuitSolver object at 0x00000166CEEE4CE0>   │ │
│ │           t_max = 0.001                                                 │ │
│ │       time_step = 0.001                                                 │ │
│ │   VoltageSource = <class 'components.components.VoltageSource'>         │ │
│ │       Voltmeter = <class 'components.instruments.Voltmeter'>            │ │
│ │       voltmeter = <components.instruments.Voltmeter object at           │ │
│ │                   0x00000166CFC994C0>                                   │ │
│ │            Wire = <class 'components.components.Wire'>                  │ │
│ └─────────────────────────────────────────────────────────────────────────┘ │
│                                                                             │
│ C:\Users\Матвей\Desktop\sirius-leto-master\src_drafts\lab5_circuit\solver.p │
│ y:167 in solve                                                              │
│                                                                             │
│   164 │   │   incrementer = self.circuit._increment(self.time_step)         │
│   165 │   │                                                                 │
│   166 │   │   for _ in r:                                                   │
│ > 167 │   │   │   voltages = incrementer.__next__()                         │
│   168 │   │                                                                 │
│   169 │   │   return voltages                                               │
│   170                                                                       │
│                                                                             │
│ ┌──────────────────────────────── locals ─────────────────────────────────┐ │
│ │           _ = 0                                                         │ │
│ │ incrementer = <generator object Circuit._increment at                   │ │
│ │               0x00000166CFCFD2F0>                                       │ │
│ │ progressbar = True                                                      │ │
│ │           r = <tqdm.std.tqdm object at 0x00000166CEF3A540>              │ │
│ │        self = <solver.CircuitSolver object at 0x00000166CEEE4CE0>       │ │
│ │       t_max = 0.001                                                     │ │
│ └─────────────────────────────────────────────────────────────────────────┘ │
│                                                                             │
│ C:\Users\Матвей\Desktop\sirius-leto-master\src_drafts\lab5_circuit\solver.p │
│ y:69 in _increment                                                          │
│                                                                             │
│    66 │   │   │   │   │   │   other_node_index = self.node_index[resistor.n │
│    67 │   │   │   │   │                                                     │
│    68 │   │   │   │   │   A[node_eq_index, node_eq_index] += 1 / resistor.v │
│ >  69 │   │   │   │   │   A[node_eq_index, other_node_index] -= 1 / resisto │
│    70 │   │   │   │                                                         │
│    71 │   │   │   │   for source in self.components["VoltageSource"]:       │
│    72 │   │   │   │   │   if source.node1 == node:                          │
│                                                                             │
│ ┌──────────────────────────────── locals ─────────────────────────────────┐ │
│ │             A = array([[0.       , 0.       , 0.       ],               │ │
│ │                 │      [0.       , 0.9999999, 0.       ],               │ │
│ │                 │      [0.       , 0.       , 0.       ]])              │ │
│ │             B = array([0., 0., 0.])                                     │ │
│ │          node = 'node0'                                                 │ │
│ │ node_eq_index = 1                                                       │ │
│ │      resistor = <components.components.Resistor object at               │ │
│ │                 0x00000166CEF54860>                                     │ │
│ │          self = <solver.Circuit object at 0x00000166CEE9A360>           │ │
│ │          time = 0                                                       │ │
│ │     time_step = 0.001                                                   │ │
│ │      voltages = {'ground': 0, 'node0': 0, 'node1': 0}                   │ │
│ └─────────────────────────────────────────────────────────────────────────┘ │
└─────────────────────────────────────────────────────────────────────────────┘
UnboundLocalError: cannot access local variable 'other_node_index' where it is 
not associated with a value

Process finished with exit code 1

**Comment by wsadqert** [comment]
да, с `UnboundLocalError` моя ошибка - я вынес кусок кода за if-elif, забыв про else. И если ни одно условие в if-elif не выполнялось, возникала ошибка

**Comment by wsadqert** [comment]
- [x] ~~debug `UnboundLocalError`~~
- [x] ~~fix incorrect ammeter behaviour~~

all done, wait for patch

**Comment by wsadqert** [comment]
fixed by https://github.com/wsadqert/sirius-leto/commit/f88625a19a02797875a0fcbb8c420ffa0e4e3add
